
export const
  UPDATE_PARAMS = 'UPDATE_PARAMS',
  ACTION_LIST = 'ACTION_LIST',
  ACTION_DETAIL = 'ACTION_DETAIL',
  ACTION_UPDATE = 'ACTION_UPDATE',
  ACTION_ADD = 'ACTION_ADD',
  ACTION_DEL = 'ACTION_DEL';
